/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2018 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>

#include <math.h>

#define ADC_DEADZONE 2 // Threshold at which ADC will not be considered as 0. (to compensate for noise)

ISR(TIMER2_OVF_vect)
{
	/* Insert your TIMER_0 timer overflow interrupt handling code here */
	
	adc_result_t adc_res;
	
	ADC_0_enable();
	adc_res = ADC_0_get_conversion(2);	// Start conversion on channel 2 and wait for result
	ADC_0_disable();
	
	if (adc_res > ADC_DEADZONE)
	{
		PWM_0_enable();
		PWM_0_load_duty_cycle_ch0(pow(2, ((double)(adc_res + 1.0) / 64.0)) - 1); // Converts linear response to "anti-log" (to compensate for eye brightness perception), and Set PWM duty cycle to converted ADC value
		sleep_set_mode(SLEEP_MODE_IDLE);	// Sleep mode allowing Tim1 clk so that PWM continues to work
	} else {
		PWM_0_disable();
		sleep_set_mode(SLEEP_MODE_PWR_SAVE);	// Deeper sleep mode than Idle, Tim1 clk not active (no PWM), Tim2 clk still active (Tim2 overflow is the wake up triggger)
	}
}
